In [2]:
import pandas as pd
import matplotlib.pyplot as plt
#%matplotlib inline
from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
import seaborn as sns
import numpy as np

In [45]:
def predict(x,w):
    total_stimulation = np.dot(x,w)
    if total_stimulation > 0:
        y_pred = 1
    else:
        y_pred = -1
    return y_pred
    


-1
-1
-1
-1
-1
1
1
1
1
1


In [51]:
X = np.arange(-25,25).reshape(10,5)

ones = np.ones((X.shape[0],1))
X_1 = np.append(X,ones,1)
w = np.random.rand(X_1.shape[1])
print('Initial w:')
print(w)

# for i in range(len(X_1)):
#     print(predict(X_1[i,],w))

y = np.array([1, -1, -1, 1, -1, 1, -1, -1, 1, -1])
eta = 0.01

epochs = 10

for epoch in range(epochs):
    for x, y_target in zip(X_1,y):
        y_pred = predict(x,w)
        delta_w = eta*(y_target-y_pred)*x
        w += delta_w
        print(w)
    
    


Initial w:
[0.98667975 0.41671857 0.24252506 0.79475586 0.17337144 0.48285825]
[ 0.48667975 -0.06328143 -0.21747494  0.35475586 -0.24662856  0.50285825]
[ 0.48667975 -0.06328143 -0.21747494  0.35475586 -0.24662856  0.50285825]
[ 0.48667975 -0.06328143 -0.21747494  0.35475586 -0.24662856  0.50285825]
[ 0.28667975 -0.24328143 -0.37747494  0.21475586 -0.36662856  0.52285825]
[ 0.38667975 -0.16328143 -0.31747494  0.25475586 -0.34662856  0.50285825]
[ 0.38667975 -0.14328143 -0.27747494  0.31475586 -0.26662856  0.52285825]
[ 0.38667975 -0.14328143 -0.27747494  0.31475586 -0.26662856  0.52285825]
[ 0.38667975 -0.14328143 -0.27747494  0.31475586 -0.26662856  0.52285825]
[0.68667975 0.17671857 0.06252506 0.67475586 0.11337144 0.54285825]
[ 0.28667975 -0.24328143 -0.37747494  0.21475586 -0.36662856  0.52285825]
[ 0.28667975 -0.24328143 -0.37747494  0.21475586 -0.36662856  0.52285825]
[ 0.68667975  0.13671857 -0.01747494  0.55475586 -0.04662856  0.50285825]
[ 0.68667975  0.13671857 -0.01747494  0